# Generated by Django 5.0.2 on 2024-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('service_fee', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
