<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-05-21 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pricemodel'),
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-05-24 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pricemodel'),
        ),
    ]
>>>>>>> a127b27b62cb185cc2c7a418d8f3485fc8c8969d
