<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-05-02 16:50
=======
#<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-05-01 18:57
#=======
# Generated by Django 5.0.2 on 2024-05-02 08:12
#>>>>>>> f7ed58c931d28a3c91b0270470d6cd1debddd60a
>>>>>>> ab1e35c2f95964e2eb2dbf05cd20c0de5797dfc8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pricemodel'),
        ),
    ]
