# Generated by Django 5.0.2 on 2024-04-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='cost_per_delivery',
            new_name='service_fee',
        ),
    ]
