# Generated by Django 5.1.1 on 2024-12-06 23:20

import django.db.models.deletion
import encrypted_model_fields.fields
import sample.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('labs', '0001_initial'),
        ('modelmixins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('health_insuarance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', encrypted_model_fields.fields.EncryptedCharField()),
                ('message', encrypted_model_fields.fields.EncryptedCharField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelmixins.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_id', models.CharField(default=sample.models.generate_referral_id, editable=False, max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('Laboratory', 'Laboratory'), ('Hospital', 'Hospital')], max_length=255)),
                ('patient_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('patient_age', encrypted_model_fields.fields.EncryptedCharField()),
                ('patient_sex', encrypted_model_fields.fields.EncryptedCharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('clinical_history', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('attachment', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('requires_phlebotomist', encrypted_model_fields.fields.EncryptedBooleanField(default=False)),
                ('sender_full_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('sender_phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('sender_email', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('referral_status', models.CharField(choices=[('Request Made', 'Request Made'), ('Request Terminated', 'Request Terminated'), ('Request Accepted', 'Request Accepted'), ('Delivery Pick-up', 'Delivery Pick-up'), ('Request Completed', 'Request Completed'), ('Sample Received', 'Sample Received')], max_length=100)),
                ('date_referred', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.delivery')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='modelmixins.facility')),
                ('to_laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelmixins.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralTrackingHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Request Made', 'Request Made'), ('Request Terminated', 'Request Terminated'), ('Request Accepted', 'Request Accepted'), ('Delivery Pick-up', 'Delivery Pick-up'), ('Request Completed', 'Request Completed'), ('Sample Received', 'Sample Received')], db_index=True, max_length=50)),
                ('location', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_history', to='sample.referral')),
            ],
            options={
                'verbose_name_plural': 'Referral Trackings',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sample.referral')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelmixins.sampletype')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Not Initialized', 'Not Initialized'), ('Pending Results Upload', 'Pending Results Upload'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=50)),
                ('result', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_tests', to='sample.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='labs.test')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTrackingHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Rejected', 'Rejected')], db_index=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_history', to='sample.sample')),
            ],
            options={
                'verbose_name_plural': 'Sample Trackings',
            },
        ),
    ]
