# Generated by Django 5.0.3 on 2024-06-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('hospital', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('Laboratory', 'Laboratory'), ('Hospital', 'Hospital')], max_length=50)),
                ('sender_full_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(max_length=254)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.DateField()),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('clinical_history', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sample/attachments')),
                ('status', models.CharField(choices=[('received', 'receive sample'), ('rejected', 'reject sample')], max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_accessed_by_lab', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hospital.facility')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.sampletype')),
                ('tests', models.ManyToManyField(related_name='tests', to='labs.test')),
                ('to_laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.branch')),
            ],
        ),
    ]
