# Generated by Django 5.0.3 on 2024-05-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('hospital', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_full_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(max_length=254)),
                ('name_of_patient', models.CharField(max_length=200)),
                ('patient_age', models.DateTimeField(auto_now=True)),
                ('patient_sex', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=200)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sample/attachments')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_accessed_by_lab', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hospital.facility')),
                ('tests', models.ManyToManyField(related_name='tests', to='labs.test')),
                ('to_laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.branch')),
            ],
        ),
    ]
