# Generated by Django 5.0.3 on 2024-05-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='name_of_patient',
            new_name='patient_name',
        ),
    ]
