# Generated by Django 5.0.3 on 2024-06-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
        migrations.AddField(
            model_name='sample',
            name='collect_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='mark_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='reject_sample',
            field=models.BooleanField(default=False),
        ),
    ]
