# Generated by Django 5.0.3 on 2024-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rename_name_of_patient_sample_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='patient_age',
            field=models.DateField(),
        ),
    ]
