# Generated by Django 5.1.1 on 2024-12-06 23:20

import datetime
import encrypted_model_fields.fields
import transactions.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_requests', models.PositiveIntegerField(default=0)),
                ('amortized_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_withdrawn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Free Plan', max_length=100)),
                ('duration', models.DurationField(default=datetime.timedelta(days=9999))),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_renewed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('has_expired', models.BooleanField(default=False)),
                ('date_of_subscription', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', encrypted_model_fields.fields.EncryptedCharField()),
                ('channels', encrypted_model_fields.fields.EncryptedCharField()),
                ('email', encrypted_model_fields.fields.EncryptedEmailField()),
                ('payment_mode', encrypted_model_fields.fields.EncryptedCharField(choices=[('Online', 'Online'), ('Bank', 'Bank'), ('Insurance', 'Insurance')])),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50)),
                ('is_verified', encrypted_model_fields.fields.EncryptedBooleanField(default=False)),
                ('reference', models.CharField(default='<function uuid4 at 0x000001A53A6BAC00>', max_length=36, unique=True, validators=[transactions.models.validate_reference])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
