# Generated by Django 5.0.3 on 2024-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_requests', models.PositiveIntegerField(default=0)),
                ('amortized_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_withdrawn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Free Plan', max_length=100)),
                ('duration', models.DurationField(default='9999 days')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_renewed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('has_expired', models.BooleanField(default=False)),
                ('date_of_subscription', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Bank', 'Bank')], max_length=50)),
                ('service_paid', models.CharField(max_length=100)),
                ('date_paid', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
