# Generated by Django 5.0.2 on 2024-04-19 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
