# Generated by Django 5.0.2 on 2024-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DurationField(default='30 days'),
        ),
    ]
