# Generated by Django 5.0.2 on 2024-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
