# Generated by Django 5.0.2 on 2024-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
