# Generated by Django 5.0.2 on 2024-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_subscription_balance_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
