# Generated by Django 5.0.2 on 2024-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DurationField(default='999999999 days'),
        ),
    ]
