# Generated by Django 5.0.2 on 2024-04-19 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_incentive_beneficient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account_number', models.PositiveIntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Bank', 'Bank')], max_length=50)),
                ('service_paid', models.CharField(max_length=100)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
