# Generated by Django 5.0.2 on 2024-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='clients/profile/picture'),
        ),
    ]
