# Generated by Django 5.0.2 on 2024-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_a_delivery',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_a_lab',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_a_clinician',
        ),
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Clinician', 'Clinician'), ('Delivery', 'Delivery')], default='Laboratory', max_length=100),
            preserve_default=False,
        ),
    ]
