# Generated by Django 5.0.2 on 2024-05-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='emmergency_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='client',
            name='staff_id',
        ),
    ]
