# Generated by Django 5.0.2 on 2024-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Health Worker', 'Health Worker'), ('Delivery', 'Delivery')], max_length=100),
        ),
    ]
