# Generated by Django 5.0.3 on 2024-05-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Hospital', 'Hospital'), ('Delivery', 'Delivery')], max_length=100),
        ),
    ]
