# Generated by Django 5.0.2 on 2024-04-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_client_has_a_delivery_remove_client_has_a_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('laboratory', 'laboratory'), ('clinician', 'clinician'), ('delivery', 'delivery')], max_length=100),
        ),
    ]
