# Generated by Django 5.0.2 on 2024-05-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_is_admin_client_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_admin',
        ),
    ]
