# Generated by Django 5.0.2 on 2024-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_client_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Clinician', 'Clinician'), ('Delivery', 'Delivery')], max_length=100),
        ),
    ]
