# Generated by Django 5.0.2 on 2024-05-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_client_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_branch_manager',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_general_manager',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_health_worker',
        ),
    ]
