# Generated by Django 5.0.2 on 2024-04-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_client_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='facility_affiliated_with',
            new_name='current_facility',
        ),
    ]
