# Generated by Django 5.0.2 on 2024-03-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('ward_type', models.CharField(choices=[('Male Ward', 'Male Ward'), ('Female Ward', 'Female Ward'), ('Surgical Ward', 'Surgical Ward'), ('Children Ward', 'Children Ward')], max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('ward_manager', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('hospital_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=50)),
                ('digital_address', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wards', models.ManyToManyField(related_name='hospital_wards', to='hospital.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('sample_type', models.CharField(max_length=200)),
                ('sample_container', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_access_by_lab', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.laboratory')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='labs.test')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.ward')),
            ],
        ),
    ]
