<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-04-30 14:27
=======
# Generated by Django 5.0.2 on 2024-04-30 14:38
>>>>>>> 74f6721958802aec09a77e343ad2a973c3a625fe

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.laboratory'),
        ),
    ]
