# Generated by Django 5.0.2 on 2024-03-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_initial'),
        ('hospital', '0001_initial'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='sample',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.laboratory'),
        ),
        migrations.AddField(
            model_name='sample',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='tests',
            field=models.ManyToManyField(to='labs.test'),
        ),
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='sample',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.ward'),
        ),
    ]
