# Generated by Django 5.0.2 on 2024-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
