# Generated by Django 5.0.2 on 2024-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='tests',
            field=models.ManyToManyField(related_name='tests', to='labs.test'),
        ),
    ]
