# Generated by Django 5.0.3 on 2024-05-24 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='adminstrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='sender_email',
            field=models.EmailField(default='tim@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='sender_full_name',
            field=models.CharField(default='timo', max_length=200),
            preserve_default=False,
        ),
    ]
