# Generated by Django 5.0.2 on 2024-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='sample/attachments'),
        ),
    ]
