# Generated by Django 5.0.2 on 2024-05-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
        ('labs', '0003_alter_testresult_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.branch'),
        ),
    ]
