<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='patient_age',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='patient_age',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
>>>>>>> 137df379a06e45fab26352dbe5531d2f2944f24a
