# Generated by Django 5.0.2 on 2024-05-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_age',
            field=models.PositiveIntegerField(),
        ),
    ]
