# Generated by Django 5.0.3 on 2024-05-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_adminstrator_sample_sender_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='send_by',
            new_name='adminstrator',
        ),
    ]
