# Generated by Django 5.0.2 on 2024-04-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('hospital', '0005_alter_sample_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
            preserve_default=False,
        ),
    ]
