# Generated by Django 5.0.3 on 2024-05-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_send_by_sample_adminstrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='adminstrator',
            new_name='administrator',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='is_access_by_lab',
            new_name='is_accessed_by_lab',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='adminstrator',
        ),
        migrations.AddField(
            model_name='sample',
            name='sender_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
