# Generated by Django 5.0.2 on 2024-04-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('hospital', '0006_alter_sample_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
    ]
