# Generated by Django 5.0.3 on 2024-05-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_adminstrator_hospital_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='mailing_address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='account_number',
            field=models.CharField(default='P.O Box, 45', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_address',
            field=models.CharField(default='P.O Box, 45', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='referral_percent_discount',
            field=models.CharField(default='35%', max_length=5),
            preserve_default=False,
        ),
    ]
