# Generated by Django 5.0.2 on 2024-04-27 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_sample_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='patient_age',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
