# Generated by Django 5.0.2 on 2024-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('heard_of_department', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department_name', models.CharField(choices=[('Haematology', 'Haematology'), ('Microbiology', 'Microbiology'), ('Parasitology', 'Parasitology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Molecular Biology', 'Molecular Biology')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('digital_address', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(default='logo.png', upload_to='labs/logo')),
                ('herfra_id', models.CharField(max_length=100, verbose_name='HERFRA ID')),
                ('website', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('laboratory', models.CharField(max_length=200)),
                ('result', models.FileField(upload_to='labs/results')),
                ('comments', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
