# Generated by Django 5.0.2 on 2024-05-18 06:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)])),
                ('main_phone', models.CharField(max_length=15)),
                ('main_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(default='logo.png', upload_to='labs/logo')),
                ('herfra_id', models.CharField(max_length=100, verbose_name='HERFRA ID')),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(db_column='General manager', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
                'unique_together': {('laboratory_name',)},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_phone', models.CharField(max_length=15)),
                ('branch_email', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('digital_address', models.CharField(max_length=15)),
                ('region', models.CharField(choices=[('Northern', 'Northern'), ('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('Savannah', 'Savannah'), ('Bono', 'Bono'), ('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Central', 'Central'), ('Volta', 'Volta'), ('North East', 'North East'), ('Bono East', 'Bono East'), ('Oti', 'Oti'), ('Ashanti', 'Ashanti')], max_length=100)),
                ('branch_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='labs.laboratory')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turn_around_time', models.CharField(max_length=200)),
                ('patient_preparation', models.TextField()),
                ('branch', models.ManyToManyField(db_index=True, related_name='tests', to='labs.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorySample',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_patient', models.CharField(max_length=200)),
                ('patient_age', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_sex', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=200)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sample/attachments')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_access_by_lab', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('from_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.branch')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_samples', to='labs.branch')),
                ('tests', models.ManyToManyField(related_name='tests_requested', to='labs.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='labs/results')),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.branch')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital.hospital')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.sample')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.test')),
            ],
        ),
    ]
