# Generated by Django 5.0.2 on 2024-05-12 00:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_phone', models.CharField(max_length=15)),
                ('branch_email', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('digital_address', models.CharField(max_length=15)),
                ('region', models.CharField(choices=[('Northern', 'Northern'), ('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('Savannah', 'Savannah'), ('Bono', 'Bono'), ('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Central', 'Central'), ('Volta', 'Volta'), ('North East', 'North East'), ('Bono East', 'Bono East'), ('Oti', 'Oti'), ('Ashanti', 'Ashanti')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(200)])),
                ('main_phone', models.CharField(max_length=15)),
                ('main_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(default='logo.png', upload_to='labs/logo')),
                ('herfra_id', models.CharField(max_length=100, verbose_name='HERFRA ID')),
                ('website', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.CreateModel(
            name='LaboratorySample',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_patient', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_sex', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=200)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sample/attachments')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_access_by_lab', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turn_around_time', models.DurationField(default='02:00:00')),
                ('patient_preparation', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='labs/results')),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
