# Generated by Django 5.0.2 on 2024-05-02 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_initial'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='created_by',
            field=models.ForeignKey(db_column='General manager', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='labs.laboratory'),
        ),
        migrations.AddField(
            model_name='test',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='labs.branch'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.branch'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.sample'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.test'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratory',
            unique_together={('laboratory_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('branch', 'name')},
        ),
    ]
