# Generated by Django 5.0.2 on 2024-04-22 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_initial'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='labs.laboratory'),
        ),
        migrations.AddField(
            model_name='test',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='labs.department'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.department'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.laboratory'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.test'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratory',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('laboratory', 'department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('department', 'name')},
        ),
    ]
