# Generated by Django 5.0.2 on 2024-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='region_of_location',
            field=models.CharField(default='Northern Region', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='town_of_location',
            field=models.CharField(default='TTH', max_length=255),
            preserve_default=False,
        ),
    ]
