# Generated by Django 5.0.2 on 2024-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorysample',
            name='patient_age',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
