# Generated by Django 5.0.2 on 2024-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
