# Generated by Django 5.0.2 on 2024-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorysample',
            name='patient_age',
            field=models.PositiveIntegerField(),
        ),
    ]
