# Generated by Django 5.0.3 on 2024-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
