# Generated by Django 5.0.2 on 2024-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dicount_price',
            field=models.FloatField(default=15.31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Haematology', 'Haematology'), ('Microbiology', 'Microbiology'), ('Parasitology', 'Parasitology'), ('Clinical Chemistry', 'Clinical Chemistry'), ('Molecular Biology', 'Molecular Biology')], max_length=100),
        ),
    ]
