# Generated by Django 5.0.2 on 2024-05-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('labs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name_of_patient', models.CharField(max_length=200)),
                ('patient_age', models.DateField()),
                ('patient_sex', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=200)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sample/attachments')),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_received_by_delivery', models.BooleanField(default=False)),
                ('is_delivered_to_lab', models.BooleanField(default=False)),
                ('is_access_by_lab', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('from_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.branch')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(related_name='tests_requested', to='labs.test')),
                ('to_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_samples', to='labs.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
