# Generated by Django 5.0.2 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
