# Generated by Django 5.0.2 on 2024-04-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_sample_delivery'),
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.sample'),
            preserve_default=False,
        ),
    ]
