# Generated by Django 5.0.3 on 2024-05-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorysample',
            old_name='is_access_by_lab',
            new_name='is_accessed_by_lab',
        ),
    ]
