# Generated by Django 5.0.2 on 2024-04-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.department'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.test'),
        ),
    ]
