# Generated by Django 5.0.2 on 2024-03-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_test_dicount_price_alter_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='dicount_price',
            new_name='discount_price',
        ),
    ]
