# Generated by Django 5.0.2 on 2024-05-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_laboratorysample'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
    ]
