# Generated by Django 5.0.2 on 2024-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_laboratorysample_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorysample',
            name='patient_age',
            field=models.DateTimeField(default='Age'),
        ),
    ]
