# Generated by Django 5.0.3 on 2024-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_rename_is_access_by_lab_laboratorysample_is_accessed_by_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='sample_type',
            field=models.ManyToManyField(to='labs.sampletype'),
        ),
    ]
